# -*- coding: utf-8 -*-
"""ATS_Fit_Score_Colab_GPU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plUO80dsy03CGN_mHEdsSc5MDtCWmWZb

# ATS Fit Score Regression — Google Colab GPU Version

Pipeline: CrossEncoder regression for resume-job ATS score prediction.

Use GPU: `Runtime` → `Change runtime type` → `T4 GPU`.
"""


"""## Option A: Upload train.csv and validation.csv manually"""

from google.colab import files

uploaded = files.upload()
print(uploaded.keys())

"""## Option B: Load dataset directly from Hugging Face
Run this cell only if you do not upload CSV files manually.
"""

# Optional Hugging Face loading
# from datasets import load_dataset
# ds = load_dataset("0xnbk/resume-ats-score-v1-en")
# print(ds)
# ds["train"].to_pandas().to_csv("train.csv", index=False)
# ds["validation"].to_pandas().to_csv("validation.csv", index=False)

"""## Training"""

import os
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)


TRAIN_PATH = "train.csv"
VAL_PATH = "validation.csv"

MODEL_NAME = "bert-base-uncased"
OUTPUT_DIR = "models/ats_regression_model"

MAX_LENGTH = 512
EPOCHS = 3
BATCH_SIZE = 4
LEARNING_RATE = 2e-5
SEED = 42


def split_text(text):
    text = str(text)

    if "[SEP]" in text:
        candidate, job = text.split("[SEP]", 1)
    else:
        candidate, job = text, ""

    return candidate.strip(), job.strip()


class ATSDataset(torch.utils.data.Dataset):
    def __init__(self, df, tokenizer):
        self.texts_a = []
        self.texts_b = []
        self.labels = []

        for _, row in df.iterrows():
            candidate, job = split_text(row["text"])
            self.texts_a.append(candidate)
            self.texts_b.append(job)
            self.labels.append(float(row["ats_score"]) / 100.0)

        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        encoded = self.tokenizer(
            self.texts_a[idx],
            self.texts_b[idx],
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH,
            return_tensors="pt",
        )

        item = {k: v.squeeze(0) for k, v in encoded.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.float)

        return item


def load_data(path):
    df = pd.read_csv(path)

    df = df.dropna(subset=["text", "ats_score"]).copy()
    df["ats_score"] = pd.to_numeric(df["ats_score"], errors="coerce")
    df = df.dropna(subset=["ats_score"])
    df["ats_score"] = df["ats_score"].clip(0, 100)

    return df


def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    preds = predictions.reshape(-1)
    labels = labels.reshape(-1)

    preds = np.clip(preds, 0.0, 1.0)

    preds_100 = preds * 100.0
    labels_100 = labels * 100.0

    mae = mean_absolute_error(labels_100, preds_100)
    rmse = math.sqrt(mean_squared_error(labels_100, preds_100))
    r2 = r2_score(labels_100, preds_100)

    return {
        "mae": mae,
        "rmse": rmse,
        "r2": r2,
    }


def main():
    Path("models").mkdir(exist_ok=True)

    print("CUDA available:", torch.cuda.is_available())

    train_df = load_data(TRAIN_PATH)
    val_df = load_data(VAL_PATH)

    print("Train size:", len(train_df))
    print("Validation size:", len(val_df))

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    train_dataset = ATSDataset(train_df, tokenizer)
    val_dataset = ATSDataset(val_df, tokenizer)

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=1,
        problem_type="regression",
    )

    training_args = TrainingArguments(
        output_dir="checkpoints",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=EPOCHS,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="mae",
        greater_is_better=False,
        save_total_limit=2,
        fp16=False,
        bf16=False,
        logging_steps=50,
        report_to="none",
        seed=SEED,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        callbacks=[
            EarlyStoppingCallback(early_stopping_patience=2)
        ],
    )

    trainer.train()

    metrics = trainer.evaluate()
    print(metrics)

    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    final_metrics = {
        "MAE": round(float(metrics["eval_mae"]), 4),
        "RMSE": round(float(metrics["eval_rmse"]), 4),
        "R2": round(float(metrics["eval_r2"]), 4),
    }

    with open("models/metrics.json", "w") as f:
        json.dump(final_metrics, f, indent=2)

    print("Final metrics:")
    print(final_metrics)

    print("Model saved to:", OUTPUT_DIR)


if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')

"""## Prediction function"""

def predict_ats_score(candidate_text, job_description):
    pred = model.predict([[candidate_text, job_description]])[0]
    pred = float(np.clip(pred, 0.0, 1.0) * 100.0)
    return round(pred, 2)

candidate = "Python programmer with 5 years of experience programming."
job = "We need a machine learning engineer with Python and NLP skills."

predict_ats_score(candidate, job)

"""## Save model archive and download"""

